[db]
  data-source = "postgresql://postgres.ahrqchqzjdwgwruczixw:Turaka@200222@aws-0-ap-south-1.pooler.supabase.com:5432/postgres"
  prepare-stmt = true
  log-level = 1
  [db.pool]
    enable = true
    max-idle-connections = 25
    max-lifetime = "10m"
    max-open-connections = 25

[cronjobs]
  enable = true

[jwt]
  allowed-users = [""]
  secret = "883f5a85b0e1fcda8eecb18bc1f0f0ecf19db408ef0015b5280d6b69b3692344"
  session-time = "30d"

[log]
  development = true
  level = -1

[server]
  graceful-shutdown = "15s"
  port = 8080
  read-timeout = "1h"
  write-timeout = "1h"

[tg]
  app-hash = "3f37e0cef9d7294e6d6a3bb6177e39d6"
  app-id = 26097333
  app-version = "4.6.3 K"
  bg-bots-limit = 5
  device-model = "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/116.0"
  disable-stream-bots = false
  lang-code = "en"
  lang-pack = "webk"
  rate = 100
  rate-burst = 50
  rate-limit = true
  session-file = ""
  system-lang-code = "en-US"
  system-version = "Win32"
  
  [tg.uploads]
    encryption-key = ""
    retention = "7d"
    threads = 8
  [tg.stream]
    multi-threads = 16
    buffers = 32

